[package]
name = "serialization"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
itertools = "0.14.0"
quote = "1"
walkdir = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.12"
proc-macro2 = "1.0"
